credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: 'pbkdf2:sha256:260000$Fak3H@sh3dP@ss'  # use stauth.Hasher to generate
cookie:
  name: saas_dashboard
  key: some_secret_key
  expiry_days: 30
